name: forex

services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - path: .env
        required: true
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local